about_page <- div(
  h4("Johns Hopkins University"),
  h5("Course: Data Visualization By Instructor Mohammad Ali Alamdar Yazdi"),
          
  tags$div(class = "card border-light mb-3",
           style = "max-width: 100rem;",
           tags$div(class = "card-header", 
                    "Methodology"),
           tags$div(class = "card-body", 
                    tags$p(class = "card-title",
                            "Worldcloud"),
                    tags$p(class = "card-text",
                           "worldcloud methoud is used to visualize the most frequent words.In the wordcloud visualization, color and size of each word represents its frequency")),
           tags$div(class = "card-body",
                    tags$p(class = "card-title",
                           "Ggplot Plotly"),
                    tags$p(class = "card-text",
                           "In Twitter, we use ggplot to display the number of tweets for a particular hour, day, week, and month to show the popularity of the search term. In gtends, it is also used to show entry heat, trendline. What's more, we also use ggplot to do a sentiment analysis, to figure out the respond of people to vocabulary.For using plotly, it provides more specific data in graph ")),
           tags$div(class = "card-body",
                    tags$p(class = "card-title",
                           "Text Mining"),
                    tags$p(class = "card-text",
                           "In the dashboard page, using text mining methods, we extract the frequency of each word."))
           ),
  
  tags$div(class = "shadow p-3 mb-5 bg-body rounded", 
           class = "card-group",
           tags$div(class = "card",
                    tags$img(src = "...",
                             class = "card-img-top",
                             alt = "..."),
                    tags$div(class = "card-body",
                             tags$h6(class = "card-title",
                                     "Han Liu"),
                             tags$p(class = "card-text",
                                    a(href = "lh971016@gmail.com","lh971016@gmail.com")))),
           tags$div(class = "card",
                    tags$img(src = "...",
                             class = "card-img-top",
                             alt = "..."),
                    tags$div(class = "card-body",
                             tags$h6(class = "card-title",
                                     "Minghao Du"),
                             tags$p(class = "card-text",
                                    a(href = "minghaodu96@gmail.com","minghaodu96@gmail.com")))),
           tags$div(class = "card",
                    tags$img(src = "...",
                             class = "card-img-top",
                             alt = "..."),
                    tags$div(class = "card-body",
                             tags$h6(class = "card-title",
                                     "Mengying Zhao"),
                             tags$p(class = "card-text",
                                    a(href = "mailto:zymm48@gmail.com","zymm48@gmail.com")))),
           tags$div(class = "card",
                    tags$img(src = "...",
                             class = "card-img-top",
                             alt = "..."),
                    tags$div(class = "card-body",
                             tags$h6(class = "card-title",
                                     "Wenlu Chen"),
                             tags$p(class = "card-text",
                                    a(href = "Wenlu3412@gmail.com","Wenlu3412@gmail.com")))),
           tags$div(class = "card",
                    tags$img(src = "...",
                             class = "card-img-top",
                             alt = "..."),
                    tags$div(class = "card-body",
                             tags$h6(class = "card-title",
                                     "Yanlin Li"),
                             tags$p(class = "card-text",
                                    a(href = "l3pphadct@gmail.com","l3pphadct@gmail.com"))))),
  
  tags$div(class = "card border-light mb-3",
           style = "max-width: 100rem;",
           tags$div(class = "card-header",
                    "Reference"),
           tags$div(class = "card-body",
                    tags$h5(class = "card-title",
                            "Twitter"),
                    tags$p(class = "card-text",
                           a(href = "https://twitter.com/explore","https://twitter.com/explore"))), 
           tags$div(class = "card-body",
                    tags$h5(class = "card-title",
                            "Gtrends"),
                    tags$p(class = "card-text",
                           a(href = "https://trends.google.com/trends/?geo=US","https://trends.google.com/trends/?geo=US"))),  
           tags$div(class = "card-body",
                    tags$p(class = "card-title",
                           "Reddit"),
                    tags$p(class = "card-text",
                           a(href="https://www.reddit.com/r/raddit/","https://www.reddit.com/r/raddit/")))
  ),
           )
          